### ISSUE TITLE
After uploading the zip file the app gets stuck in the insta logo

### ISSUE THREAD

**Issue by eth206** [mainigautam/instagram_backup_manager#13]
![Screenshot 2022-07-31 030511](https://user-images.githubusercontent.com/74795341/182005313-f7d38e1e-0302-4243-be30-9cbc1f7f928f.png)

**Comment by mainigautam** [comment]
**Keep The Command prompt from start.bat open otherwise application will not work , in screenshot i can you you closed the terminal**
Perform the above step and try again if still doesn't work check the following things
1). Firstly please check you are using branch with latest changes
2). Check the zip file is not modified and correct 
3). Share the screenshot of the command window after uploading the backup file

**Comment by mainigautam** [comment]
Fixed it Buddy
